CREATE TABLE APP_USER (
    ID BIGSERIAL PRIMARY KEY
    ,USERNAME VARCHAR(100) NOT NULL UNIQUE
    ,EMAIL VARCHAR(255) NOT NULL UNIQUE
    ,PASSWORD_HASH VARCHAR(255) NOT NULL
    ,FIRST_NAME VARCHAR(150)
    ,LAST_NAME VARCHAR(150)
    ,IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE
    ,IS_SUPERUSER BOOLEAN NOT NULL DEFAULT FALSE
    ,CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PERMISSION (
    ID BIGSERIAL PRIMARY KEY
    ,CODE VARCHAR(100) NOT NULL UNIQUE
    ,NAME VARCHAR(150) NOT NULL
    ,DESCRIPTION TEXT
    ,IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE
    ,CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PERMISSION_USER (
    ID BIGSERIAL PRIMARY KEY
    ,USER_ID BIGINT NOT NULL
    ,PERMISSION_ID BIGINT NOT NULL
    ,ASSIGNED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,UNIQUE (USER_ID, PERMISSION_ID)
    ,CONSTRAINT FK_PERMISSION_USER_USER
        FOREIGN KEY (USER_ID)
        REFERENCES APP_USER (ID)
        ON DELETE CASCADE
    ,CONSTRAINT FK_PERMISSION_USER_PERMISSION
        FOREIGN KEY (PERMISSION_ID)
        REFERENCES PERMISSION (ID)
        ON DELETE CASCADE
);

CREATE TABLE ROLE (
    ID BIGSERIAL PRIMARY KEY
    ,CODE VARCHAR(100) NOT NULL UNIQUE
    ,NAME VARCHAR(150) NOT NULL
    ,DESCRIPTION TEXT
    ,IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE
    ,CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ROLE_PERMISSION (
    ID BIGSERIAL PRIMARY KEY
    ,ROLE_ID BIGINT NOT NULL
    ,PERMISSION_ID BIGINT NOT NULL
    ,ASSIGNED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,UNIQUE (ROLE_ID, PERMISSION_ID)
    ,CONSTRAINT FK_ROLE_PERMISSION_ROLE
        FOREIGN KEY (ROLE_ID)
        REFERENCES ROLE (ID)
        ON DELETE CASCADE
    ,CONSTRAINT FK_ROLE_PERMISSION_PERMISSION
        FOREIGN KEY (PERMISSION_ID)
        REFERENCES PERMISSION (ID)
        ON DELETE CASCADE
);

CREATE TABLE ROLE_USER (
    ID BIGSERIAL PRIMARY KEY
    ,USER_ID BIGINT NOT NULL
    ,ROLE_ID BIGINT NOT NULL
    ,ASSIGNED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,UNIQUE (USER_ID, ROLE_ID)
    ,CONSTRAINT FK_ROLE_USER_USER
        FOREIGN KEY (USER_ID)
        REFERENCES APP_USER (ID)
        ON DELETE CASCADE
    ,CONSTRAINT FK_ROLE_USER_ROLE
        FOREIGN KEY (ROLE_ID)
        REFERENCES ROLE (ID)
        ON DELETE CASCADE
);

CREATE TABLE DEPARTMENT (
    ID BIGSERIAL PRIMARY KEY
    ,CODE VARCHAR(100) NOT NULL UNIQUE
    ,NAME VARCHAR(150) NOT NULL
    ,DESCRIPTION TEXT
    ,IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE
    ,CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DEPARTMENT_USER (
    ID BIGSERIAL PRIMARY KEY
    ,DEPARTMENT_ID BIGINT NOT NULL
    ,USER_ID BIGINT NOT NULL
    ,ASSIGNED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,UNIQUE (DEPARTMENT_ID, USER_ID)
    ,CONSTRAINT FK_DEPARTMENT_USER_DEPARTMENT
        FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENT (ID)
        ON DELETE CASCADE
    ,CONSTRAINT FK_DEPARTMENT_USER_USER
        FOREIGN KEY (USER_ID)
        REFERENCES APP_USER (ID)
        ON DELETE CASCADE
);

CREATE TABLE PUBLICATION (
    ID BIGSERIAL PRIMARY KEY
    ,TITLE VARCHAR(255) NOT NULL
    ,CONTENT TEXT
    ,STATUS VARCHAR(50) NOT NULL DEFAULT 'DRAFT'
    ,CREATED_BY BIGINT
    ,IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE
    ,CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,CONSTRAINT FK_PUBLICATION_CREATED_BY
        FOREIGN KEY (CREATED_BY)
        REFERENCES APP_USER (ID)
        ON DELETE SET NULL
);

CREATE TABLE PUBLICATION_DEPARTMENT (
    ID BIGSERIAL PRIMARY KEY
    ,PUBLICATION_ID BIGINT NOT NULL
    ,DEPARTMENT_ID BIGINT NOT NULL
    ,ASSIGNED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,UNIQUE (PUBLICATION_ID, DEPARTMENT_ID)
    ,CONSTRAINT FK_PUBLICATION_DEPARTMENT_PUBLICATION
        FOREIGN KEY (PUBLICATION_ID)
        REFERENCES PUBLICATION (ID)
        ON DELETE CASCADE
    ,CONSTRAINT FK_PUBLICATION_DEPARTMENT_DEPARTMENT
        FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENT (ID)
        ON DELETE CASCADE
);

CREATE TABLE PUBLICATION_USER (
    ID BIGSERIAL PRIMARY KEY
    ,PUBLICATION_ID BIGINT NOT NULL
    ,USER_ID BIGINT NOT NULL
    ,ASSIGNED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,UNIQUE (PUBLICATION_ID, USER_ID)
    ,CONSTRAINT FK_PUBLICATION_USER_PUBLICATION
        FOREIGN KEY (PUBLICATION_ID)
        REFERENCES PUBLICATION (ID)
        ON DELETE CASCADE
    ,CONSTRAINT FK_PUBLICATION_USER_USER
        FOREIGN KEY (USER_ID)
        REFERENCES APP_USER (ID)
        ON DELETE CASCADE
);

CREATE TABLE DOCUMENT (
    ID BIGSERIAL PRIMARY KEY
    ,TITLE VARCHAR(255) NOT NULL
    ,FILE_NAME VARCHAR(255) NOT NULL
    ,FILE_BINARY BYTEA NOT NULL
    ,MIME_TYPE VARCHAR(150)
    ,FILE_SIZE BIGINT
    ,DESCRIPTION TEXT
    ,UPLOADED_BY BIGINT
    ,IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE
    ,CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,CONSTRAINT FK_DOCUMENT_UPLOADED_BY
        FOREIGN KEY (UPLOADED_BY)
        REFERENCES APP_USER (ID)
        ON DELETE SET NULL
);

CREATE TABLE DOCUMENT_USER (
    ID BIGSERIAL PRIMARY KEY
    ,DOCUMENT_ID BIGINT NOT NULL
    ,USER_ID BIGINT NOT NULL
    ,ASSIGNED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,UNIQUE (DOCUMENT_ID, USER_ID)
    ,CONSTRAINT FK_DOCUMENT_USER_DOCUMENT
        FOREIGN KEY (DOCUMENT_ID)
        REFERENCES DOCUMENT (ID)
        ON DELETE CASCADE
    ,CONSTRAINT FK_DOCUMENT_USER_USER
        FOREIGN KEY (USER_ID)
        REFERENCES APP_USER (ID)
        ON DELETE CASCADE
);

CREATE TABLE DOCUMENT_DEPARTMENT (
    ID BIGSERIAL PRIMARY KEY
    ,DOCUMENT_ID BIGINT NOT NULL
    ,DEPARTMENT_ID BIGINT NOT NULL
    ,ASSIGNED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,UNIQUE (DOCUMENT_ID, DEPARTMENT_ID)
    ,CONSTRAINT FK_DOCUMENT_DEPARTMENT_DOCUMENT
        FOREIGN KEY (DOCUMENT_ID)
        REFERENCES DOCUMENT (ID)
        ON DELETE CASCADE
    ,CONSTRAINT FK_DOCUMENT_DEPARTMENT_DEPARTMENT
        FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENT (ID)
        ON DELETE CASCADE
);